### PR TITLE
Load balance, and restart failing services

### PR DESCRIPTION
**Pull request by palvarez89**
Now we can  have N uwsgi services (I've decided that 2 was a good number).
Nginx will send requests to both of them. In the case that a uwsgi service
starts eating the cpu, monit will reload and/or restart it.

Nginx will not send request to uwsgi services that are not running, minimizing
the impact of these service reloads/restarts.

With this in place in production, we can all sit back, relax, and enjoy life :)

### CODE REVIEW

**Comment by palvarez89** [comment]
I have managed somehow to test this without a real case scenario, but it would be good someone could have a look at it.

**Comment by Mariocj89** [comment]
Will we receive an email when monit restars the wsgis?

**Comment by palvarez89** [comment]
Yes, we will have emails for anything in monit.

**Comment by Mariocj89** [comment]
Looks good to me. Feel free to merge

**Pull request merged**
